# **Data Cleaning Assignment : Pythonic Data Cleaning With pandas and NumPy**


Link: https://realpython.com/python-data-cleaning-numpy-pandas/

In [1]:
# import required modules

import pandas as pd
import numpy as np

**Dropping Columns in a DataFrame**

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/realpython/python-data-cleaning/refs/heads/master/Datasets/BL-Flickr-Images-Book.csv')
df.head()

,Identifier,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL,Shelfmarks
0,206,NaN,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12641.b.30.
1,216,NaN,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12626.cc.2.
2,218,NaN,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12625.dd.1.
3,472,NaN,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10369.bbb.15.
4,480,"A new edition, revised, etc.",London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9007.d.28.

In [3]:
to_drop = ['Edition Statement',
           'Corporate Author',
            'Corporate Contributors',
            'Former owner',
            'Engraver',
            'Contributors',
            'Issuance type',
            'Shelfmarks']

df.drop(to_drop, inplace=True, axis=1)
# inplace=True makes the changes permanent and directly in our object
# axis=1 means column. so, we're dropping columns

In [4]:
df.head()

,Identifier,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
0,206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
1,216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
2,218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
3,472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
4,480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...

In [5]:
# Alternatively, we could also remove the columns by passing them to the columns parameter directly
# instead of separately specifying the labels to be removed and the axis where pandas should look for the labels:

# df.drop(columns=to_drop, inplace=True)

# This syntax is more intuitive and readable. What we’re trying to do here is directly apparent.

**Changing the Index of a DataFrame**

In [6]:
df['Identifier'].is_unique

True

In [7]:
df = df.set_index('Identifier') # replace the existing index with this column using set_index
df.head()

# if inplace=True not written, the replacement / changes is done on the copied table and not on the original table
# not done directly on the object

,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
Identifier,,,,,,
206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...

In [8]:
df.loc[206] # get record or row using label (value in 'Identifier' column)

Place of Publication                                               London
Date of Publication                                           1879 [1878]
Publisher                                                S. Tinsley & Co.
Title                                   Walter Forbes. [A novel.] By A. A
Author                                                              A. A.
Flickr URL              http://www.flickr.com/photos/britishlibrary/ta...
Name: 206, dtype: object

In [9]:
# OG included code, but not included since error is returned
#df.set_index('Identifier', inplace=True)
# inplace=True makes the changes directly in the object / original table

**Tidying up Fields in the Data**

In [10]:
# compromised method as the OG returns error.
# the original is: df.get_dtype_counts().counts()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8287 entries, 206 to 4160339
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Place of Publication  8287 non-null   object
 1   Date of Publication   8106 non-null   object
 2   Publisher             4092 non-null   object
 3   Title                 8287 non-null   object
 4   Author                6509 non-null   object
 5   Flickr URL            8287 non-null   object
dtypes: object(6)
memory usage: 711.2+ KB

In [11]:
df.loc[1905:, 'Date of Publication'].head(10)
# 1905: is to get values/records from Identifier column starting from 1905 till end (index / string slicing)
# putting 'Date of Publication' means to get only that column aside from 1905:/Identifier column

Identifier
1905           1888
1929    1839, 38-54
2836           1897
2854           1865
2956        1860-63
2957           1873
3017           1866
3131           1899
4598           1814
4884           1820
Name: Date of Publication, dtype: object

In [12]:
regex = r'^(\d{4})'

# The \d represents any digit, and {4} repeats this rule four times.
# The ^ character matches the start of a string
# the parentheses denote a capturing group, which signals to pandas that we want to extract that part of the regex.
 # (We want ^ to avoid cases where [ starts off the string.)

# The regular expression above is meant to find any four digits at the beginning of a string
# 'r' is a raw string (meaning that a backslash is no longer an escape character),
# which is standard practice with regular expressions.

In [13]:
extr = df['Date of Publication'].str.extract(r'^(\d{4})', expand=False)
extr.head()

Identifier
206    1879
216    1868
218    1869
472    1851
480    1857
Name: Date of Publication, dtype: object

In [14]:
df['Date of Publication'] = pd.to_numeric(extr)
df['Date of Publication'].dtype

# changes of 'Date of Publication' column dtype to numeric
# from object
# This results in about one in every ten values being missing,

dtype('float64')

In [15]:
df['Date of Publication'].isnull().sum() / len(df)

# counts the percentage of missing value in the column

np.float64(0.11717147339205986)

**Combining str Methods with NumPy to Clean Columns**

In [16]:
# we can combine pandas str methods with NumPy’s np.where function,
# which is basically a vectorized form of Excel’s IF() macro
# the syntax is: np.where(condition, then, else)

# 'condition' is either an array-like object or a Boolean mask
# 'then' is the value to be used if 'condition' evaluates to True
# 'else' is the value to be used otherwise
# .where() takes each element in the object used for condition,
# checks whether that particular element evaluates to True in the context of the condition,
# and returns an ndarray containing then or else, depending on which applies.

# It can be nested into a compound if-then statement, allowing us to compute values based on multiple conditions:
# >>> np.where(condition1, x1,
#        np.where(condition2, x2,
#            np.where(condition3, x3, ...)))

# we'll use these two functions to clean Place of Publication since this column has string objects

In [17]:
df['Place of Publication'].head(10)

Identifier
206                                  London
216                London; Virtue & Yorston
218                                  London
472                                  London
480                                  London
481                                  London
519                                  London
667     pp. 40. G. Bryan & Co: Oxford, 1898
874                                 London]
1143                                 London
Name: Place of Publication, dtype: object

In [18]:
df.loc[4157862]

Place of Publication                                  Newcastle-upon-Tyne
Date of Publication                                                1867.0
Publisher                                                      T. Fordyce
Title                   Local Records; or, Historical Register of rema...
Author                      FORDYCE, T. - Printer, of Newcastle-upon-Tyne
Flickr URL              http://www.flickr.com/photos/britishlibrary/ta...
Name: 4157862, dtype: object

In [19]:
df.loc[4159587]

Place of Publication                                  Newcastle upon Tyne
Date of Publication                                                1834.0
Publisher                                                Mackenzie & Dent
Title                   An historical, topographical and descriptive v...
Author                                              Mackenzie, E. (Eneas)
Flickr URL              http://www.flickr.com/photos/britishlibrary/ta...
Name: 4159587, dtype: object

In [20]:
# The two books above were published in the same place, but one has hyphens in the name of the place while the other does not.
# To clean this column in one sweep, we can use str.contains() to get a Boolean mask.

In [21]:
pub = df['Place of Publication']
london = pub.str.contains('London')
london[:5]

Identifier
206    True
216    True
218    True
472    True
480    True
Name: Place of Publication, dtype: bool

In [22]:
oxford = pub.str.contains('Oxford')
oxford[:5]

Identifier
206    False
216    False
218    False
472    False
480    False
Name: Place of Publication, dtype: bool

In [23]:
df['Place of Publication'] = np.where(london, 'London',
                                      np.where(oxford, 'Oxford',
                                               pub.str.replace('-', ' ')))

In [24]:
df['Place of Publication'].head()

Identifier
206    London
216    London
218    London
472    London
480    London
Name: Place of Publication, dtype: object

In [25]:
df.head()

,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
Identifier,,,,,,
206,London,1879.0,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
216,London,1868.0,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869.0,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851.0,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857.0,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...

**Cleaning the Entire Dataset Using the applymap Function**

In [32]:
# creating a list of (state, city) tuples and wrapping that list in a DataFrame
# file source: https://github.com/realpython/python-data-cleaning/blob/master/Datasets/university_towns.txt
# upload the file to GC

university_towns = []
with open('university_towns.txt') as file:
  for line in file:
    if '[edit]' in line:
      # Remember this `state` until the next is found
      state = line
    else:
      # Otherwise, we have a city; keep `state` as last-seen
      university_towns.append((state, line))

university_towns[:5]

[('Alabama[edit]\n', 'Auburn (Auburn University)[1]\n'),
 ('Alabama[edit]\n', 'Florence (University of North Alabama)\n'),
 ('Alabama[edit]\n', 'Jacksonville (Jacksonville State University)[2]\n'),
 ('Alabama[edit]\n', 'Livingston (University of West Alabama)[2]\n'),
 ('Alabama[edit]\n', 'Montevallo (University of Montevallo)[2]\n')]

In [33]:
# set the columns as “State” and “RegionName”
# pandas will take each element in the list and set State to the left value and RegionName to the right value

towns_df = pd.DataFrame(university_towns,
                        columns=['State', 'RegionName'])

towns_df.head()

             State                                         RegionName
0  Alabama[edit]\n                    Auburn (Auburn University)[1]\n
1  Alabama[edit]\n           Florence (University of North Alabama)\n
2  Alabama[edit]\n  Jacksonville (Jacksonville State University)[2]\n
3  Alabama[edit]\n       Livingston (University of West Alabama)[2]\n
4  Alabama[edit]\n         Montevallo (University of Montevallo)[2]\n

In [39]:
def get_citystate(item):
  if ' (' in item:
    return item[:item.find(' (')]
    # [:item.find()] is a string slicing to extract string before ' ('
    # [start:end], empty start means starts from index 0 of str
    # the end is ' (' and will not be included in the returned output
  elif '[' in item:
    return item[:item.find('[')]
  else:
    return item

In [40]:
# pandas’ .map() only takes one parameter,
# which is the function (callable) that should be applied to each element

towns_df =  towns_df.map(get_citystate)

# The applymap() method took each element from the DataFrame,
# passed it to the function, and the original value was replaced by the returned value.

In [41]:
towns_df.head()

     State    RegionName
0  Alabama        Auburn
1  Alabama      Florence
2  Alabama  Jacksonville
3  Alabama    Livingston
4  Alabama    Montevallo

**Renaming Columns and Skipping Rows**

In [43]:
# rename columns and skip certain rows so that we can drill down to necessary information with correct and sensible labels
# file source: https://github.com/realpython/python-data-cleaning/blob/master/Datasets/olympics.csv
# upload the file to GC

olympics_df = pd.read_csv('olympics.csv')
olympics_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,NaN,? Summer,01 !,02 !,03 !,Total,? Winter,01 !,02 !,03 !,Total,? Games,01 !,02 !,03 !,Combined total
1,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
2,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
3,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
4,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12

In [48]:
olympics_df = pd.read_csv('olympics.csv', header=1)
# can use index_col=0 instead of header=1 to get rid of the "Unnamed: 0" column
# and making the first column the first column + get rid of the index number on the left
olympics_df.head()

,Unnamed: 0,? Summer,01 !,02 !,03 !,Total,? Winter,01 !.1,02 !.1,03 !.1,Total.1,? Games,01 !.2,02 !.2,03 !.2,Combined total
0,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
1,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
2,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
3,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
4,Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

In [49]:
# defining a dictionary that maps current column names (as keys) to more usable ones (the dictionary’s values)

new_names =  {'Unnamed: 0': 'Country',
              '? Summer': 'Summer Olympics',
              '01 !': 'Gold',
              '02 !': 'Silver',
              '03 !': 'Bronze',
              '? Winter': 'Winter Olympics',
              '01 !.1': 'Gold.1',
              '02 !.1': 'Silver.1',
              '03 !.1': 'Bronze.1',
              '? Games': '# Games',
              '01 !.2': 'Gold.2',
              '02 !.2': 'Silver.2',
              '03 !.2': 'Bronze.2'}

In [51]:
# To rename the columns, we will make use of a DataFrame’s rename() method,
# which allows you to relabel an axis based on a mapping (in this case, a dict)
# call the rename() function on our object

olympics_df.rename(columns=new_names, inplace=True)

# Setting inplace to True specifies that our changes be made directly to the object

In [52]:
olympics_df.head()

,Country,Summer Olympics,Gold,Silver,Bronze,Total,Winter Olympics,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
0,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
1,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
2,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
3,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
4,Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

**Python Data Cleaning: Recap and Resources**

In [28]:
# In this tutorial, you learned how you can drop unnecessary information from a dataset using the drop() function,
# as well as how to set an index for your dataset so that items in it can be referenced easily.

# Moreover, you learned how to clean object fields with the .str() accessor
# and how to clean the entire dataset using the applymap() method.
# Lastly, we explored how to skip rows in a CSV file and rename columns using the rename() method.

# Knowing about data cleaning is very important, because it is a big part of data science.
# You now have a basic understanding of how pandas and NumPy can be leveraged to clean datasets!